### ISSUE TITLE
Security vulnerability (two levels down)

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt-less#102]
Report from `npm audit`

```
Low             Regular Expression Denial of Service

Package         clean-css

Patched in      >=4.1.11

Dependency of   roosevelt-less

Path            roosevelt-less > less-plugin-clean-css > clean-css

More info       https://nodesecurity.io/advisories/785
```

[less-plugin-clean-css](https://www.npmjs.com/package/less-plugin-clean-css) has an [open issue](https://github.com/less/less-plugin-clean-css/issues/26) on it.

Note: For what it is worth, it seems less-plugin-clean-css hasn't been touched in awhile, may be abandoned?

**Comment by kethinov** [comment]
As I understand it, the severity of this issue is quite low. You'd have to get compromised code into the build process of your app, in which case your app would already be compromised. Also I think it's a bit hasty to declare the project abandoned.

Since the issue is with a dependency and it doesn't seem particularly severe, I'm going to close this. Reopen if the severity is greater than it appears (justifying putting serious effort into a fork/rewrite) or if a direct solution we can implement quickly presents itself.
